% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Oct-2023 00:14:51
%  MATLAB version: 9.14.0.2206163 (R2023a)
% -------------------------------------------------------------------
saveVarsMat = load('PID_coef.mat');

kd = 0.0824380679349514;

ki = 0.12628634535922;

kp = 115.072226705239;

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

clear saveVarsMat;
